---
title: "Samenvatting - papers"
author: "Jarno Jacob Duiker"
date: "2025-04-28"
output: html_document
bibliography: bibliography.bib
---

## Vereisten

Voor het schrijven van een paper zul je je moeten verdiepen in de wetenschappelijke literatuur. Het lezen van artikelen kost tijd en kun je ook leren. Om dit als team te doen gaan jullie elkaar helpen. Ieder teamlid leest 2 artikelen vat deze samen zodat het team de essentie van het artikel kan begrijpen.

Schrijf 2 samenvattingen over papers die gerelateerd zijn aan je onderzoeksopdracht.

De samenvatting (geschreven in het Nederlands, zónder gebruik van AI) moet het volgende bevatten:

-Eigen woorden (dus geen vertalingen van zinnen)

-Introductie, waar je ook externe bronnen mag gebruiken om onbekende termen of technieken uit kan leggen. Hier beschrijf je de onderzoeksvraag en de leg je de (belangrijkste) methoden uit, eventueel met figuren

-Beschrijf waarom de methode die auteurs hebben gekozen geschikt is voor dit onderzoek

-Beschijf de belangrijkste resultaten en beschrijf ook minstens 1 figuur uit de resultaten

-Een korte samenvatting van de eindconclusie (in eigen woorden)

De samenvatting is géén abstract

## Gekozen papers

Eerste paper - @boyer2013 - Informatie over "bile" en het belang er voor in de lever. Dit is een paper die met ons onderzoek te maken heeft omdat ons onderzoek veel gebruik maakt van "bile" samples. Hierom is het handig om te begrijpen wat het is, Hoe het ontstaat, waarvoor het gebruikt word en de compositie. Dit word in dit artikel beschreven en zal ik samenvatten tot een netjes en leesbaar geheel.

Tweede paper - @singh2019 - Multi-omics omvat een groot aantal tools, Na analyse van verschillende tools zoals MoFA+, Multi-Anova en andere statistische tools leek Diablo mij erg interessant. Dit is om meerdere redenen, Diablo kan kijken naar verschillende omics waaronder Transcript- & proteomics wat in onze research paper de data is, en Diablo zoekt identificeert essentiele moleculaire stuurders.

# Introductie - @boyer2013 - 

Bile ook wel Gal, een bitter gele vloeistof die gemaakt word in de lever. Dit gal is essentieel voor de functie van het lichaam maar ook essentieel voor lever transplantatie. Een gal monster kan worden uitgelezen voor eiwit patronen wat de onderzoekers veel kan vertellen. Omdat gal ook een belangrijk onderdeel is van het gekozen hoofd onderzoek is het belangrijk om wat achtergrond info hierover te verkrijgen. Deze samenvatting zal gaan over wat de algemene functies zijn van gal, waaruit gal is opgemaakt en welke dingen in deze structuur belangrijk zijn voor het gekozen hoofd onderzoek, en nog wat extra dingen die het artikel @boyer2013 als belangrijk benoemd. Het artikel komt uit een tijdschrift genaamd "Comprehensive Physiology" Dit tijdschrift publiceerd artikelen in het interdisciplenaire vled van inter-orgaan communicatie in gezeondheid en ziekte. Onderwerpen die dit tijdschrijft behandeld zijn inter-orgaan cellulaire communicatie, signaal paden, orgaan overspraak, systeem biologie, inter-orgaan pathologie en pathogenesis, de rol van hormonen en neurotransmitters. Het tijdschrift heeft naast artikelen ook reviews en editorials @comprehe . Dit is belangrijk om te zien of het artikel wel van kwaliteit is. Artikelen die gepubliceerd zijn in Tijdschrijften moeten langs een keuring van wetenschaps journalisten waardoor het artikel betrouwbaarder is.

**Wat is gal precies en waar word het gemaakt?**

Gal is een vloeistof wat gemaakt word in lever maar word bewaard in je galblaas. De gal vloeistof bestaat uit veel dingen voornamelijk water, ongeveer 95% van gal bestaat uit water. Andere dingen die in gal te vinden zijn Elektrolyten dit zijn stofjes die natuurlijke positief of negatief geladen zijn wanneer ze opgelost zijn in water. Elektrolyten helpen je lichaam in regulatie van chemische reacties, zorgen voor de balans tussen vloeistof binnen en buiten de cellen en spiercontractie. Ze zijn ook essentieel om medische problemen en ziekten te identificeren. Organische Anionen (een ion met een negatieve lading, gelijk aan het aantal opgenomen elektronen) zoals Gal zouten, Gal zouten bestaan uit Steroïden zuren, primairy zuren zoals cholic zuur en chenodeoxycholic zuur of secondaire zuren zoals deoxycholic zuur en lithocholic zuur.
**Wat is de functie van gal?**

**De terug koppeling tussen dit onderzoek en het gekozen hoofd onderzoek.**

**Extra belangerijke info**

# Introductie - @singh2019

Multi-omics is een relatief nieuw veld de eerste publicaties kwamen uit 2006 waarna de publicaties per jaar in 2018-2020 fors steeg. Multi-omics is de vergelijking van meerdere data uit de verschillende omics velden met elkaar en hierin een link leggen. Neem bijvoorbeeld het linken van Genen (DNA-genomics) en de proteinen (proteomics) die zorgen voor problemen bij de patiënten. Dit kan nu gedaan worden met verschillende tools zoals MoFA+, Multi-Anova, of Diablo. In deze samenvatting ga ik het hebben over de Diablo tool. De diablo tool kijkt in het kort naar de verschillende datasets die het heeft gekregen en zoekt plus identificeert essentiele moleculaire stuurders. Deze kunnen dan in een na-analyse worden bekeken voor functie en of invloed op de patiënt.
